services:
  web:
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-cd=_*5^%8npx7&!nn(fxov)m!tz%c%_92=ym7*cp=rzkgc&=bs
      - DJANGO_SETTINGS_MODULE=snipbox.settings

